### ISSUE TITLE
[Bug]: install fails

### ISSUE THREAD

**Issue by adamjimenez** [webdevnerdstuff/vuetify3-resize-drawer#13]
### Bug description

```
npm i vuetify3-resize-drawer
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/vuetify3-resize-drawer - Not found
npm ERR! 404
npm ERR! 404  'vuetify3-resize-drawer@*' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

### Steps to reproduce

Install with npm

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by webdevnerdstuff** [comment]
The component is still in Beta and not ready for production. There is an outstanding Vuetify bug I'm waiting to be fixed.

**Comment by adamjimenez** [comment]
Thank you! What was the related Vuetify bug?
Perhaps the readme should reflect this current status.

**Comment by webdevnerdstuff** [comment]
[[Bug Report][3.1.5] v-nagivation-drawer width prop as string breaks functionality and causes layout issues with v-main](https://github.com/vuetifyjs/vuetify/issues/16705). 

You can see the issue on my demo page. Notice how the resize drawer on the left side doesn't push the main layout like the regular drawer on the other size?
https://webdevnerdstuff.github.io/vuetify3-resize-drawer/

Also the readme already has `(beta)` in it. ;)

**Comment by webdevnerdstuff** [comment]
I went ahead and published it, just in case so nobody else could take the name. I haven't tested anything out with it yet though.
https://www.npmjs.com/package/vuetify3-resize-drawer
